#!/bin/bash
# ========================================
# Cron Jobs Setup for Cold Outreach Scripts
# ========================================
# This script sets up automatic scheduling on VPS
# Run this script ON THE VPS after deployment

SCRIPT_DIR="/root/cold-outreach"

echo "======================================="
echo "Cron Jobs Setup"
echo "======================================="
echo ""
echo "This will setup automatic scheduling for:"
echo "1. Apollo Lead Collection - Daily at 9:00 AM"
echo "2. Email Campaign Sync - Every 6 hours"
echo "3. Results Backup - Daily at midnight"
echo ""
read -p "Continue? (y/n): " confirm

if [ "$confirm" != "y" ]; then
    echo "Aborted"
    exit 0
fi

# Backup existing crontab
crontab -l > /tmp/crontab_backup_$(date +%Y%m%d_%H%M%S).txt 2>/dev/null
echo "✓ Existing crontab backed up"

# Create new crontab
cat > /tmp/new_crontab << 'EOF'
# Cold Outreach Automation - Cron Jobs
# Generated by setup_cron_jobs.sh

# Apollo Lead Collection - Every day at 9:00 AM Bali time
0 9 * * * cd /root/cold-outreach && /usr/bin/python3 modules/apollo/scripts/apollo_lead_collector.py >> /root/cold-outreach/logs/apollo_$(date +\%Y\%m\%d).log 2>&1

# Instantly Campaign Sync - Every 6 hours
0 */6 * * * cd /root/cold-outreach && /usr/bin/python3 modules/instantly/scripts/instantly_sync.py >> /root/cold-outreach/logs/instantly_$(date +\%Y\%m\%d).log 2>&1

# Email Scraping - Every Monday at 10:00 AM
0 10 * * 1 cd /root/cold-outreach && /usr/bin/python3 modules/scraping/scripts/simple_homepage_scraper.py --input data/raw/websites.csv >> /root/cold-outreach/logs/scraping_$(date +\%Y\%m\%d).log 2>&1

# Results Backup - Daily at midnight
0 0 * * * cd /root/cold-outreach && tar -czf backups/results_$(date +\%Y\%m\%d).tar.gz modules/*/results/*.json 2>/dev/null

# Cleanup old logs (older than 30 days) - Weekly on Sunday at 3:00 AM
0 3 * * 0 find /root/cold-outreach/logs -name "*.log" -mtime +30 -delete

EOF

# Install new crontab
crontab /tmp/new_crontab
echo "✓ Cron jobs installed"
echo ""

# Show installed cron jobs
echo "Installed cron jobs:"
echo "======================================="
crontab -l
echo "======================================="
echo ""

# Create logs directory
mkdir -p $SCRIPT_DIR/logs
mkdir -p $SCRIPT_DIR/backups
echo "✓ Created logs and backups directories"
echo ""

echo "✓ Setup complete!"
echo ""
echo "Cron schedule:"
echo "- Apollo leads: Daily at 9:00 AM"
echo "- Instantly sync: Every 6 hours"
echo "- Email scraping: Every Monday at 10:00 AM"
echo "- Backups: Daily at midnight"
echo "- Log cleanup: Weekly on Sunday"
echo ""
echo "To view logs:"
echo "  tail -f $SCRIPT_DIR/logs/apollo_$(date +%Y%m%d).log"
echo ""
echo "To edit cron jobs:"
echo "  crontab -e"
echo ""
